delete from ace_world.spell where id=5349;
insert into ace_world.spell set id=5349, name='Nether Bolt I', description="Shoots a bolt of nether at the target. The bolt does 21-52 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=5, range_Constant=30, range_Mod=0.7, power=1, economy_Mod=1, formula_Version=1, component_Loss=0, meta_Spell_Type=2, meta_Spell_Id=5349, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8032, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=21, variance=31, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5350;
insert into ace_world.spell set id=5350, name='Nether Bolt II', description="Shoots a bolt of nether at the target. The bolt does 42-84 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=10, range_Constant=30, range_Mod=0.6, power=50, economy_Mod=1, formula_Version=1, component_Loss=1028443341, meta_Spell_Type=2, meta_Spell_Id=5350, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8034, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=42, variance=42, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5351;
insert into ace_world.spell set id=5351, name='Nether Bolt III', description="Shoots a bolt of nether at the target. The bolt does 63-115 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=15, range_Constant=30, range_Mod=0.5, power=100, economy_Mod=1, formula_Version=1, component_Loss=1036831949, meta_Spell_Type=2, meta_Spell_Id=5351, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8036, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=63, variance=52, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5352;
insert into ace_world.spell set id=5352, name='Nether Bolt IV', description="Shoots a bolt of nether at the target. The bolt does 73-146 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=20, range_Constant=30, range_Mod=0.4, power=150, economy_Mod=1, formula_Version=1, component_Loss=1041865114, meta_Spell_Type=2, meta_Spell_Id=5352, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8038, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=73, variance=73, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5353;
insert into ace_world.spell set id=5353, name='Nether Bolt V', description="Shoots a bolt of nether at the target. The bolt does 84-178 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=25, range_Constant=30, range_Mod=0.3, power=200, economy_Mod=1, formula_Version=1, component_Loss=1045220557, meta_Spell_Type=2, meta_Spell_Id=5353, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8040, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=84, variance=94, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5354;
insert into ace_world.spell set id=5354, name='Nether Bolt VI', description="Shoots a bolt of nether at the target. The bolt does 105-210 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=3, mana=30, range_Constant=30, range_Mod=0.2, power=250, economy_Mod=1, formula_Version=1, component_Loss=1050253722, meta_Spell_Type=2, meta_Spell_Id=5354, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8042, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=105, variance=105, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5355;
insert into ace_world.spell set id=5355, name='Nether Bolt VII', description="Shoots a bolt of nether at the target. The bolt does 168-262 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=131, mana=35, range_Constant=30, range_Mod=0.2, power=300, economy_Mod=1, formula_Version=1, component_Loss=1041865114, meta_Spell_Type=2, meta_Spell_Id=5355, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=8043, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=168, variance=94, wcid=43230, num_Projectiles=1, spread_Angle=0;

delete from ace_world.spell where id=5356;
insert into ace_world.spell set id=5356, name='Incantation of Nether Bolt', description="Shoots a bolt of nether at the target. The bolt does 252-325 points of nether damage to the first thing it hits.", school=5, icon_Id=100691554, category=640, bitfield=131, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=1041865114, meta_Spell_Type=2, meta_Spell_Id=5356, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=198, spell_Formula_Comp_5_Component_Id=55, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5130, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, portal_Lifetime=0, stat_Mod_Type=0, stat_Mod_Key=0, stat_Mod_Val=0, e_Type=1024, base_Intensity=252, variance=73, wcid=43230, num_Projectiles=1, spread_Angle=0;