IF DEFINED APPVEYOR_PULL_REQUEST_HEAD_COMMIT (
call compile-pr.bat
7z a ..\..\ACE-World-Database-v%APPVEYOR_BUILD_VERSION%.sql.zip %APPVEYOR_PULL_REQUEST_NUMBER%-%APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH%.zip
cd ..\..
)
