/* item magic 8 */

delete from ace_world.spell where id=4391;
insert into ace_world.spell set id=4391, name="Incantation of Acid Bane", description="Increases a shield or piece of armor's resistance to acid damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673969, category=162, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4391, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4512, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=18 /* ArmorModVsAcid */, stat_Mod_Val=2;

delete from ace_world.spell where id=4392;
insert into ace_world.spell set id=4392, name="Incantation of Acid Lure", description="Decreases a shield or piece of armor's resistance to acid damage by 200%.", school=3, icon_Id=100673974, category=163, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4392, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=64, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4516, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=18 /* ArmorModVsAcid */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4393;
insert into ace_world.spell set id=4393, name="Incantation of Blade Bane", description="Increases a shield or piece of armor's resistance to slashing damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673872, category=174, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4393, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4576, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=13 /* ArmorModVsSlash */, stat_Mod_Val=2;

delete from ace_world.spell where id=4394;
insert into ace_world.spell set id=4394, name="Incantation of Blade Lure", description="Decreases a shield or piece of armor's resistance to slashing damage by 200%.", school=3, icon_Id=100673980, category=175, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4394, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=62, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4580, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=13 /* ArmorModVsSlash */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4395;
insert into ace_world.spell set id=4395, name="Aura of Incantation of Blood Drinker Self", description="Increases a weapon's damage value by 24 points.", school=3, icon_Id=100673986, category=154, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4395, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=816, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=24;

delete from ace_world.spell where id=4396;
insert into ace_world.spell set id=4396, name="Incantation of Blood Loather", description="Decreases a weapon's damage value by 24 points.", school=3, icon_Id=100673987, category=155, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4396, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=58, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4592, non_Component_Target_Type=257, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=44 /* Damage */, stat_Mod_Val=-24;

delete from ace_world.spell where id=4397;
insert into ace_world.spell set id=4397, name="Incantation of Bludgeon Bane", description="Increases a shield or piece of armor's resistance to bludgeoning damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673873, category=164, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4397, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4628, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=15 /* ArmorModVsBludgeon */, stat_Mod_Val=2;

delete from ace_world.spell where id=4398;
insert into ace_world.spell set id=4398, name="Incantation of Bludgeon Lure", description="Decreases a shield or piece of armor's resistance to bludgeoning damage by 200%.", school=3, icon_Id=100673975, category=165, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4398, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=68, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4630, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=15 /* ArmorModVsBludgeon */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4399;
insert into ace_world.spell set id=4399, name="Incantation of Brittlemail", description="Worsens a shield or piece of armor's armor value by 300 points.", school=3, icon_Id=100673981, category=161, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4399, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=143, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4642, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=28 /* ArmorLevel */, stat_Mod_Val=-300;

delete from ace_world.spell where id=4400;
insert into ace_world.spell set id=4400, name="Aura of Incantation of Defender Self", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 20%.", school=3, icon_Id=100673988, category=156, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4400, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=822, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.2;

delete from ace_world.spell where id=4401;
insert into ace_world.spell set id=4401, name="Incantation of Flame Bane", description="Increases a shield or piece of armor's resistance to fire damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673970, category=170, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4401, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4760, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=17 /* ArmorModVsFire */, stat_Mod_Val=2;

delete from ace_world.spell where id=4402;
insert into ace_world.spell set id=4402, name="Incantation of Flame Lure", description="Decreases a shield or piece of armor's resistance to fire damage by 200%.", school=3, icon_Id=100673976, category=171, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4402, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=58, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4766, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=17 /* ArmorModVsFire */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4403;
insert into ace_world.spell set id=4403, name="Incantation of Frost Bane", description="Increases a shield or piece of armor's resistance to cold damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673971, category=166, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4403, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=65, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4800, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=16 /* ArmorModVsCold */, stat_Mod_Val=2;

delete from ace_world.spell where id=4404;
insert into ace_world.spell set id=4404, name="Incantation of Frost Lure", description="Decreases a shield or piece of armor's resistance to cold damage by 200%.", school=3, icon_Id=100673977, category=167, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4404, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=66, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4806, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=16 /* ArmorModVsCold */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4405;
insert into ace_world.spell set id=4405, name="Aura of Incantation of Heart Seeker Self", description="Increases a weapon's Attack Skill modifier by 20.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4405, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=826, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=0.2;

delete from ace_world.spell where id=4406;
insert into ace_world.spell set id=4406, name="Incantation of Hermetic Void", description="Decreases a magic casting implement's mana conversion bonus by 80%.", school=3, icon_Id=100673983, category=194, bitfield=128 /* NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4406, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=68, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4888, non_Component_Target_Type=32768, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=144 /* ManaConversionMod */, stat_Mod_Val=0.2;

delete from ace_world.spell where id=4407;
insert into ace_world.spell set id=4407, name="Incantation of Impenetrability", description="Improves a shield or piece of armor's armor value by 240 points. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673982, category=160, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4407, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=142, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4890, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=28 /* ArmorLevel */, stat_Mod_Val=240;

delete from ace_world.spell where id=4408;
insert into ace_world.spell set id=4408, name="Incantation of Leaden Weapon", description="Worsens a weapon's speed by 80 points.", school=3, icon_Id=100673990, category=159, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4408, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=64, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4946, non_Component_Target_Type=257, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=49 /* WeaponTime */, stat_Mod_Val=80;

delete from ace_world.spell where id=4409;
insert into ace_world.spell set id=4409, name="Incantation of Lightning Bane", description="Increases a shield or piece of armor's resistance to electric damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673972, category=168, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4409, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5008, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=19 /* ArmorModVsElectric */, stat_Mod_Val=2;

delete from ace_world.spell where id=4410;
insert into ace_world.spell set id=4410, name="Incantation of Lightning Lure", description="Decreases a shield or piece of armor's resistance to electric damage by 200%.", school=3, icon_Id=100673978, category=169, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4410, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=68, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5016, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=19 /* ArmorModVsElectric */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4411;
insert into ace_world.spell set id=4411, name="Incantation of Lure Blade", description="Decreases the Melee Defense skill modifier of a weapon or magic caster by 20%.", school=3, icon_Id=100673985, category=157, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4411, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=62, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5038, non_Component_Target_Type=33025, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=29 /* WeaponDefense */, stat_Mod_Val=-0.2;

delete from ace_world.spell where id=4412;
insert into ace_world.spell set id=4412, name="Incantation of Piercing Bane", description="Increases a shield or piece of armor's resistance to piercing damage by 200%. Target yourself to cast this spell on all of your equipped armor.", school=3, icon_Id=100673973, category=172, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4412, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5190, non_Component_Target_Type=6, mana_Mod=14, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=14 /* ArmorModVsPierce */, stat_Mod_Val=2;

delete from ace_world.spell where id=4413;
insert into ace_world.spell set id=4413, name="Incantation of Piercing Lure", description="Decreases a shield or piece of armor's resistance to piercing damage by 200%.", school=3, icon_Id=100673979, category=173, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4413, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=60, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5192, non_Component_Target_Type=6, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=14 /* ArmorModVsPierce */, stat_Mod_Val=-2;

delete from ace_world.spell where id=4414;
insert into ace_world.spell set id=4414, name="Aura of Incantation of Spirit Drinker Self", description="Increases the elemental damage bonus of an elemental magic caster by 8%.", school=3, icon_Id=100676645, category=695, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4414, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=838, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.08;

delete from ace_world.spell where id=4415;
insert into ace_world.spell set id=4415, name="Incantation of Spirit Loather", description="Decreases the elemental damage bonus of an elemental magic caster by 8%.", school=3, icon_Id=100676646, category=155, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4415, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=58, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5250, non_Component_Target_Type=32768, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=152 /* ElementalDamageMod */, stat_Mod_Val=-0.08;

delete from ace_world.spell where id=4416;
insert into ace_world.spell set id=4416, name="Incantation of Strengthen Lock", description="Increases a lock's resistance to picking by 250 points.", school=3, icon_Id=100668401, category=192, bitfield=128 /* NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4416, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5268, non_Component_Target_Type=640, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=38 /* ResistLockpick */, stat_Mod_Val=250;

delete from ace_world.spell where id=4417;
insert into ace_world.spell set id=4417, name="Aura of Incantation of Swift Killer Self", description="Improves a weapon's speed by 80 points.", school=3, icon_Id=100673991, category=158, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4417, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=842, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-80;

delete from ace_world.spell where id=4418;
insert into ace_world.spell set id=4418, name="Aura of Incantation of Hermetic Link Self", description="Increases a magic casting implement's mana conversion bonus by 80%.", school=3, icon_Id=100673984, category=195, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4418, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=830, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.8;

delete from ace_world.spell where id=4419;
insert into ace_world.spell set id=4419, name="Incantation of Turn Blade", description="Decreases a weapon's Attack Skill modifier by 20.0 percentage points.", school=3, icon_Id=100673992, category=153, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4419, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=60, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5276, non_Component_Target_Type=257, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36872 /* Float, SingleStat, Additive */, stat_Mod_Key=62 /* WeaponOffense */, stat_Mod_Val=-0.2;

delete from ace_world.spell where id=4420;
insert into ace_world.spell set id=4420, name="Incantation of Weaken Lock", description="Decreases a lock's resistance to picking by 250 points.", school=3, icon_Id=100668401, category=193, bitfield=145 /* Resistable, Reversed, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4420, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=57, caster_Effect=0, target_Effect=60, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5306, non_Component_Target_Type=640, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=36868 /* Int, SingleStat, Additive */, stat_Mod_Key=38 /* ResistLockpick */, stat_Mod_Val=-250;

delete from ace_world.spell where id=5182;
insert into ace_world.spell set id=5182, name="Aura of Incantation of Spirit Drinker", description="Increases the elemental damage bonus of an elemental magic caster by 8%.", school=3, icon_Id=100676645, category=695, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5182, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=832, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.08;

delete from ace_world.spell where id=5183;
insert into ace_world.spell set id=5183, name="Aura of Incantation of Blood Drinker Self", description="Increases a weapon's damage value by 24 points.", school=3, icon_Id=100673986, category=154, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5183, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=818, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=24;

delete from ace_world.spell where id=5989;
insert into ace_world.spell set id=5989, name="Aura of Incantation of Hermetic Link Other", description="Increases a magic casting implement's mana conversion bonus by 80%.", school=3, icon_Id=100673984, category=195, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5989, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=828, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.8;

/* couldn't find BloodDrinkerOther8 */

delete from ace_world.spell where id=5998;
insert into ace_world.spell set id=5998, name="Aura of Incantation of Blood Drinker Other", description="Increases a weapon's damage value by 22 points.", school=3, icon_Id=100673986, category=154, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5998, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=814, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=22;

delete from ace_world.spell where id=6006;
insert into ace_world.spell set id=6006, name="Aura of Incantation of Defender Other", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 17%.", school=3, icon_Id=100673988, category=156, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6006, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=820, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.17;

delete from ace_world.spell where id=6014;
insert into ace_world.spell set id=6014, name="Aura of Incantation of Heart Seeker Other", description="Increases a weapon's Attack Skill modifier by 20.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6014, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=824, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=0.2;

delete from ace_world.spell where id=6022;
insert into ace_world.spell set id=6022, name="Aura of Incantation of Spirit Drinker Other", description="Increases the elemental damage bonus of an elemental magic caster by 8%.", school=3, icon_Id=100676645, category=695, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6022, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=834, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.08;

delete from ace_world.spell where id=6023;
insert into ace_world.spell set id=6023, name="Aura of Incantation of Spirit Drinker Other", description="Increases the elemental damage bonus of an elemental magic caster by 7%.", school=3, icon_Id=100676645, category=695, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=350, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6023, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=836, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.07;

delete from ace_world.spell where id=6031;
insert into ace_world.spell set id=6031, name="Aura of Incantation of Swift Killer Other", description="Improves a weapon's speed by 80 points.", school=3, icon_Id=100673991, category=158, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6031, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=840, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-80;
