/* life magic 8 */

delete from ace_world.spell where id=4290;
insert into ace_world.spell set id=4290, name="Incantation of Armor Other", description="Increases the target's natural armor by 250 points.", school=2, icon_Id=100668293, category=115, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4290, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=55, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4558, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=41088 /* BodyArmorValue, MultipleStat, Additive */, stat_Mod_Val=250;

delete from ace_world.spell where id=4291;
insert into ace_world.spell set id=4291, name="Incantation of Armor Self", description="Increases the caster's natural armor by 250 points.", school=2, icon_Id=100668293, category=115, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4291, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=55, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4560, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33595520 /* BodyArmorValue, MultipleStat, Additive, Beneficial */, stat_Mod_Val=250;

delete from ace_world.spell where id=4300;
insert into ace_world.spell set id=4300, name="Incantation of Enfeeble Other", description="Drains 66-131 points of the target's Stamina.", school=2, icon_Id=100668299, category=82, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=35, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=3, meta_Spell_Id=4300, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=36, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4716, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=131, damage_Type=256 /* Stamina */, boost=-66, boost_Variance=-65;

delete from ace_world.spell where id=4301;
insert into ace_world.spell set id=4301, name="Incantation of Enfeeble Self", description="Drains 50-100 points of the caster's Stamina.", school=2, icon_Id=100668299, category=82, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4301, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=36, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4718, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=100, damage_Type=256 /* Stamina */, boost=-50, boost_Variance=-50;

delete from ace_world.spell where id=4308;
insert into ace_world.spell set id=4308, name="Incantation of Harm Other", description="Drains 50-95 points of the target's Health.", school=2, icon_Id=100674016, category=80, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=35, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4308, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=32, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4856, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=95, damage_Type=128 /* Health */, boost=-50, boost_Variance=-45;

delete from ace_world.spell where id=4309;
insert into ace_world.spell set id=4309, name="Incantation of Harm Self", description="Drains 48-90 points of the caster's Health.", school=2, icon_Id=100674017, category=80, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4309, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=32, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4858, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=90, damage_Type=128 /* Health */, boost=-48, boost_Variance=-42;

delete from ace_world.spell where id=4310;
insert into ace_world.spell set id=4310, name="Incantation of Heal Other", description="Restores 90-180 points of the target's Health.", school=2, icon_Id=100674018, category=79, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4310, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=51, caster_Effect=0, target_Effect=31, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4860, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=180, damage_Type=128 /* Health */, boost=90, boost_Variance=90;

delete from ace_world.spell where id=4311;
insert into ace_world.spell set id=4311, name="Incantation of Heal Self", description="Restores 90-180 points of the caster's Health.", school=2, icon_Id=100674019, category=67, bitfield=140 /* Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4311, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=31, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4862, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=180, damage_Type=128 /* Health */, boost=90, boost_Variance=90;

delete from ace_world.spell where id=4312;
insert into ace_world.spell set id=4312, name="Incantation of Imperil Other", description="Decreases the target's natural armor by 225 points.", school=2, icon_Id=100668293, category=116, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4312, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=56, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4892, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=41088 /* BodyArmorValue, MultipleStat, Additive */, stat_Mod_Val=-225;

delete from ace_world.spell where id=4313;
insert into ace_world.spell set id=4313, name="Incantation of Imperil Self", description="Decreases the caster's natural armor by 225 points.", school=2, icon_Id=100668293, category=116, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4313, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=56, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4894, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=41088 /* BodyArmorValue, MultipleStat, Additive */, stat_Mod_Val=-225;

delete from ace_world.spell where id=4314;
insert into ace_world.spell set id=4314, name="Incantation of Mana Boost Other", description="Restores 51-100 points of the target's Mana.", school=2, icon_Id=100668288, category=83, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4314, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=35, spell_Formula_Comp_4_Component_Id=25, spell_Formula_Comp_5_Component_Id=51, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=33, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5056, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=100, damage_Type=512 /* Mana */, boost=51, boost_Variance=49;

delete from ace_world.spell where id=4315;
insert into ace_world.spell set id=4315, name="Incantation of Mana Boost Self", description="Restores 51-100 points of the caster's Mana.", school=2, icon_Id=100668288, category=83, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4315, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=35, spell_Formula_Comp_4_Component_Id=25, spell_Formula_Comp_5_Component_Id=61, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=33, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5058, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=100, damage_Type=512 /* Mana */, boost=51, boost_Variance=49;

delete from ace_world.spell where id=4316;
insert into ace_world.spell set id=4316, name="Incantation of Mana Drain Other", description="Drains 52-95 points of the target's Mana.", school=2, icon_Id=100668288, category=84, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=35, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4316, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=34, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5072, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=95, damage_Type=512 /* Mana */, boost=-52, boost_Variance=-43;

delete from ace_world.spell where id=4317;
insert into ace_world.spell set id=4317, name="Incantation of Mana Drain Self", description="Drains 48-90 points of the caster's Mana.", school=2, icon_Id=100668288, category=84, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4317, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=34, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5074, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=90, damage_Type=512 /* Mana */, boost=-48, boost_Variance=-42;

delete from ace_world.spell where id=4320;
insert into ace_world.spell set id=4320, name="Incantation of Revitalize Other", description="Restores 125-250 points of the target's Stamina.", school=2, icon_Id=100668299, category=81, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=3, meta_Spell_Id=4320, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=51, caster_Effect=0, target_Effect=35, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5220, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=250, damage_Type=256 /* Stamina */, boost=125, boost_Variance=125;

delete from ace_world.spell where id=4321;
insert into ace_world.spell set id=4321, name="Incantation of Revitalize Self", description="Restores 125-250 points of the caster's Stamina.", school=2, icon_Id=100668299, category=81, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=3, meta_Spell_Id=4321, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=35, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5222, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=250, damage_Type=256 /* Stamina */, boost=125, boost_Variance=125;

delete from ace_world.spell where id=4330;
insert into ace_world.spell set id=4330, name="Incantation of Nullify All Magic Other", description="Dispels all negative enchantments of level 8 or lower from the target.", school=2, icon_Id=100670799, category=250, bitfield=135 /* Resistable, PKSensitive, Beneficial, NotResearchable */, mana=320, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=3, component_Loss=0.35, meta_Spell_Type=9, meta_Spell_Id=4330, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=110, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=27, spell_Formula_Comp_6_Component_Id=111, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=50, caster_Effect=0, target_Effect=148, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5140, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, min_Power=0, max_Power=435, align=2 /* Negative */, number=-1, number_Variance=0;

delete from ace_world.spell where id=4331;
insert into ace_world.spell set id=4331, name="Incantation of Nullify All Magic Self", description="Dispels all negative enchantments of level 8 or lower from the caster.", school=2, icon_Id=100670799, category=250, bitfield=136 /* SelfTargeted, NotResearchable */, mana=320, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=3, component_Loss=0.35, meta_Spell_Type=9, meta_Spell_Id=4331, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=110, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=27, spell_Formula_Comp_6_Component_Id=111, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=148, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5146, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, min_Power=0, max_Power=435, align=2 /* Negative */, number=-1, number_Variance=0;

delete from ace_world.spell where id=4345;
insert into ace_world.spell set id=4345, name="Incantation of Nullify Life Magic Other", description="Dispels 3-6 negative Life Magic enchantments of level 8 or lower from the target.", school=2, icon_Id=100670802, category=250, bitfield=135 /* Resistable, PKSensitive, Beneficial, NotResearchable */, mana=320, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=3, component_Loss=0.35, meta_Spell_Type=9, meta_Spell_Id=4345, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=110, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=111, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=146, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5170, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, min_Power=0, max_Power=435, dispel_School=2 /* LifeMagic */, align=2 /* Negative */, number=6, number_Variance=0.5;

delete from ace_world.spell where id=4346;
insert into ace_world.spell set id=4346, name="Incantation of Nullify Life Magic Self", description="Dispels 3-6 negative Life Magic enchantments of level 8 or lower from the caster.", school=2, icon_Id=100670802, category=250, bitfield=136 /* SelfTargeted, NotResearchable */, mana=320, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=3, component_Loss=0.35, meta_Spell_Type=9, meta_Spell_Id=4346, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=110, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=111, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=60, caster_Effect=0, target_Effect=146, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5176, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, min_Power=0, max_Power=435, dispel_School=2 /* LifeMagic */, align=2 /* Negative */, number=6, number_Variance=0.5;

delete from ace_world.spell where id=4357;
insert into ace_world.spell set id=4357, name="Incantation of Greater Corrosive Ward", description="Reduces damage all fellowship members take from acid by 70%", school=2, icon_Id=100668344, category=101, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4357, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=49, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4822, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=69 /* ResistAcid */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4358;
insert into ace_world.spell set id=4358, name="Incantation of Greater Scythe Ward", description="Reduces damage all fellowship members take from Slashing by 70%", school=2, icon_Id=100668348, category=113, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4358, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=47, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4840, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=64 /* ResistSlash */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4359;
insert into ace_world.spell set id=4359, name="Incantation of Greater Flange Ward", description="Reduces damage all fellowship members from Bludgeoning by 70%", school=2, icon_Id=100668345, category=103, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4359, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=55, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4828, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=66 /* ResistBludgeon */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4360;
insert into ace_world.spell set id=4360, name="Incantation of Greater Frore Ward", description="Reduces damage all fellowship members take from Cold by 70%", school=2, icon_Id=100668292, category=105, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4360, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=51, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4830, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=68 /* ResistCold */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4361;
insert into ace_world.spell set id=4361, name="Incantation of Greater Inferno Ward", description="Reduces damage all fellowship members take from fire by 70%", school=2, icon_Id=100668291, category=109, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4361, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=43, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4836, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=67 /* ResistFire */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4362;
insert into ace_world.spell set id=4362, name="Incantation of Greater Voltaic Ward", description="Reduces damage all fellowship members take from Lightning by 70%", school=2, icon_Id=100668346, category=107, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4362, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=53, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4852, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=70 /* ResistElectric */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4363;
insert into ace_world.spell set id=4363, name="Incantation of Greater Lance Ward", description="Reduces damage all fellowship members take from Piercing by 70%", school=2, icon_Id=100668347, category=111, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4363, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=45, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4838, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=65 /* ResistPierce */, stat_Mod_Val=0.3;

delete from ace_world.spell where id=4364;
insert into ace_world.spell set id=4364, name="Incantation of Greater Endless Well", description="Enhances the understanding of the ebb and flow of mana. All fellowship members received a 115% increase to their nautral mana recovery rate.", school=2, icon_Id=100668288, category=97, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4364, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=190, caster_Effect=0, target_Effect=39, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4826, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=5 /* ManaRate */, stat_Mod_Val=2.15;

delete from ace_world.spell where id=4365;
insert into ace_world.spell set id=4365, name="Incantation of Greater Soothing Wind", description="Enhances the blood flow and aids in knitting wounds closed. All fellowship member receive a 115% increase to their natural health recovery rate.", school=2, icon_Id=100668279, category=93, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4365, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=190, caster_Effect=0, target_Effect=37, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4842, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=3 /* HealthRate */, stat_Mod_Val=2.15;

delete from ace_world.spell where id=4366;
insert into ace_world.spell set id=4366, name="Incantation of Greater Golden Wind", description="Enhances the intake of air and utilization of energy. All fellowship member receive a 115% increase to their natural stamina recovery rate.", school=2, icon_Id=100668299, category=95, bitfield=8334 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FellowshipSpell */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=12, meta_Spell_Id=4366, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=190, caster_Effect=0, target_Effect=41, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4832, non_Component_Target_Type=16, mana_Mod=10, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=4 /* StaminaRate */, stat_Mod_Val=2.15;

delete from ace_world.spell where id=4428;
insert into ace_world.spell set id=4428, name="Incantation of Martyr's Hecatomb", description="Drains one-quarter of the caster's health into a bolt of energy.  When struck by the bolt, the target's health is reduced by 200% of the amount drained.", school=2, icon_Id=100673244, category=80, bitfield=3 /* Resistable, PKSensitive */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=10, meta_Spell_Id=4428, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=32, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5090, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, e_Type=128 /* Health */, wcid=8607, drain_Percentage=0.25, damage_Ratio=2;

delete from ace_world.spell where id=4429;
insert into ace_world.spell set id=4429, name="Incantation of Martyr's Blight", description="Drains one-quarter of the caster's mana into a bolt of energy.  When struck by the bolt, the target's mana is reduced by 200% of the amount drained.", school=2, icon_Id=100673245, category=84, bitfield=3 /* Resistable, PKSensitive */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=10, meta_Spell_Id=4429, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=34, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5088, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, e_Type=512 /* Mana */, wcid=8604, drain_Percentage=0.25, damage_Ratio=2;

delete from ace_world.spell where id=4430;
insert into ace_world.spell set id=4430, name="Incantation of Martyr's Tenacity", description="Drains one-quarter of the caster's stamina into a bolt of energy.  When struck by the bolt, the target's stamina is reduced by 200% of the amount drained.", school=2, icon_Id=100673246, category=82, bitfield=3 /* Resistable, PKSensitive */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=10, meta_Spell_Id=4430, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=36, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5092, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, e_Type=256 /* Stamina */, wcid=8603, drain_Percentage=0.25, damage_Ratio=2;

delete from ace_world.spell where id=4459;
insert into ace_world.spell set id=4459, name="Incantation of Acid Protection Other", description="Reduces damage the target takes from acid by 68%", school=2, icon_Id=100668344, category=101, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4459, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=49, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4518, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=69 /* ResistAcid */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4460;
insert into ace_world.spell set id=4460, name="Incantation of Acid Protection Self", description="Reduces damage the caster takes from acid by 68%", school=2, icon_Id=100668344, category=101, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4460, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=49, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4520, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=69 /* ResistAcid */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4461;
insert into ace_world.spell set id=4461, name="Incantation of Blade Protection Other", description="Reduces damage the target takes from Slashing by 68%", school=2, icon_Id=100668348, category=113, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4461, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=47, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4582, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=64 /* ResistSlash */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4462;
insert into ace_world.spell set id=4462, name="Incantation of Blade Protection Self", description="Reduces damage the caster takes from Slashing by 68%", school=2, icon_Id=100668348, category=113, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4462, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=47, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4584, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=64 /* ResistSlash */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4463;
insert into ace_world.spell set id=4463, name="Incantation of Bludgeoning Protection Other", description="Reduces damage the target takes from Bludgeoning by 68%", school=2, icon_Id=100668345, category=103, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4463, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=55, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4632, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=66 /* ResistBludgeon */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4464;
insert into ace_world.spell set id=4464, name="Incantation of Bludgeoning Protection Self", description="Reduces damage the caster takes from Bludgeoning by 68%", school=2, icon_Id=100668345, category=103, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4464, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=55, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4634, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=66 /* ResistBludgeon */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4465;
insert into ace_world.spell set id=4465, name="Incantation of Cold Protection Other", description="Reduces damage the target takes from Cold by 68%", school=2, icon_Id=100668292, category=105, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4465, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=51, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4648, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=68 /* ResistCold */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4466;
insert into ace_world.spell set id=4466, name="Incantation of Cold Protection Self", description="Reduces damage the caster takes from Cold by 68%", school=2, icon_Id=100668292, category=105, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4466, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=51, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4650, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=68 /* ResistCold */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4467;
insert into ace_world.spell set id=4467, name="Incantation of Fire Protection Other", description="Reduces damage the target takes from fire by 68%", school=2, icon_Id=100668291, category=109, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4467, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=43, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4750, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=67 /* ResistFire */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4468;
insert into ace_world.spell set id=4468, name="Incantation of Fire Protection Self", description="Reduces damage the caster takes from Fire by 68%", school=2, icon_Id=100668291, category=109, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4468, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=43, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4752, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=67 /* ResistFire */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4469;
insert into ace_world.spell set id=4469, name="Incantation of Lightning Protection Other", description="Reduces damage the target takes from Lightning by 68%", school=2, icon_Id=100668346, category=107, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4469, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=53, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5018, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=70 /* ResistElectric */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4470;
insert into ace_world.spell set id=4470, name="Incantation of Lightning Protection Self", description="Reduces damage the caster takes from Lightning by 68%", school=2, icon_Id=100668346, category=107, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4470, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=53, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5020, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=70 /* ResistElectric */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4471;
insert into ace_world.spell set id=4471, name="Incantation of Piercing Protection Other", description="Reduces damage the target takes from Piercing by 68%", school=2, icon_Id=100668347, category=111, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4471, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=45, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5194, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=65 /* ResistPierce */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4472;
insert into ace_world.spell set id=4472, name="Incantation of Piercing Protection Self", description="Reduces damage the caster takes from Piercing by 68%", school=2, icon_Id=100668347, category=111, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4472, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=13, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=45, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5196, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=65 /* ResistPierce */, stat_Mod_Val=0.32;

delete from ace_world.spell where id=4473;
insert into ace_world.spell set id=4473, name="Incantation of Acid Vulnerability Other", description="Increases damage the target takes from acid by 210%.", school=2, icon_Id=100668344, category=102, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4473, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=50, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4532, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=69 /* ResistAcid */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4474;
insert into ace_world.spell set id=4474, name="Incantation of Acid Vulnerability Self", description="Increases damage the caster takes from acid by 210%.", school=2, icon_Id=100668344, category=102, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4474, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=50, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4534, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=69 /* ResistAcid */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4475;
insert into ace_world.spell set id=4475, name="Incantation of Blade Vulnerability Other", description="Increases damage the target takes from Slashing by 210%.", school=2, icon_Id=100668348, category=114, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4475, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=48, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4588, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=64 /* ResistSlash */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4476;
insert into ace_world.spell set id=4476, name="Incantation of Blade Vulnerability Self", description="Increases damage the caster takes from Slashing by 210%.", school=2, icon_Id=100668348, category=114, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4476, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=48, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4590, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=64 /* ResistSlash */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4477;
insert into ace_world.spell set id=4477, name="Incantation of Bludgeoning Vulnerability Other", description="Increases damage the target takes from Bludgeoning by 210%.", school=2, icon_Id=100668345, category=104, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4477, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=56, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4638, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=66 /* ResistBludgeon */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4478;
insert into ace_world.spell set id=4478, name="Incantation of Bludgeoning Vulnerability Self", description="Increases damage the caster takes from Bludgeoning by 210%.", school=2, icon_Id=100668345, category=104, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4478, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=56, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4640, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=66 /* ResistBludgeon */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4479;
insert into ace_world.spell set id=4479, name="Incantation of Cold Vulnerability Other", description="Increases damage the target takes from Cold by 210%.", school=2, icon_Id=100668292, category=106, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4479, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=52, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4652, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=68 /* ResistCold */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4480;
insert into ace_world.spell set id=4480, name="Incantation of Cold Vulnerability Self", description="Increases damage the caster takes from Cold by 210%.", school=2, icon_Id=100668292, category=106, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4480, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=52, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4654, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=68 /* ResistCold */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4481;
insert into ace_world.spell set id=4481, name="Incantation of Fire Vulnerability Other", description="Increases damage the target takes from Fire by 210%.", school=2, icon_Id=100668291, category=110, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4481, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=44, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4754, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=67 /* ResistFire */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4482;
insert into ace_world.spell set id=4482, name="Incantation of Fire Vulnerability Self", description="Increases damage the caster takes from Fire by 210%.", school=2, icon_Id=100668291, category=110, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4482, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=44, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4756, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=67 /* ResistFire */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4483;
insert into ace_world.spell set id=4483, name="Incantation of Lightning Vulnerability Other", description="Increases damage the target takes from Lightning by 210%.", school=2, icon_Id=100668346, category=108, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4483, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=54, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5026, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=70 /* ResistElectric */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4484;
insert into ace_world.spell set id=4484, name="Incantation of Lightning Vulnerability Self", description="Increases damage the caster takes from Lightning by 210%.", school=2, icon_Id=100668346, category=108, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4484, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=54, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5028, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=70 /* ResistElectric */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4485;
insert into ace_world.spell set id=4485, name="Incantation of Piercing Vulnerability Other", description="Increases damage the target takes from Piercing by 210%.", school=2, icon_Id=100668347, category=112, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4485, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=54, caster_Effect=0, target_Effect=46, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5198, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=65 /* ResistPierce */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4486;
insert into ace_world.spell set id=4486, name="Incantation of Piercing Vulnerability Self", description="Increases damage the caster takes from Piercing by 210%.", school=2, icon_Id=100668347, category=112, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4486, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=14, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=62, caster_Effect=0, target_Effect=46, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5200, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=65 /* ResistPierce */, stat_Mod_Val=3.1;

delete from ace_world.spell where id=4487;
insert into ace_world.spell set id=4487, name="Incantation of Exhaustion Other", description="Decreases the rate at which the target regains Stamina by 75%.", school=2, icon_Id=100668299, category=96, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4487, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=42, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4720, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=4 /* StaminaRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4488;
insert into ace_world.spell set id=4488, name="Incantation of Exhaustion Self", description="Decreases the rate at which the caster regains Stamina by 75%.", school=2, icon_Id=100668299, category=96, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4488, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=42, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4722, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=4 /* StaminaRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4489;
insert into ace_world.spell set id=4489, name="Incantation of Fester Other", description="Decrease target's natural healing rate by 75%.", school=2, icon_Id=100668279, category=94, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4489, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=38, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4736, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=3 /* HealthRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4490;
insert into ace_world.spell set id=4490, name="Incantation of Fester Self", description="Decrease caster's natural healing rate by 75%.", school=2, icon_Id=100668279, category=94, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=1, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4490, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=38, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4738, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=3 /* HealthRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4491;
insert into ace_world.spell set id=4491, name="Incantation of Mana Depletion Other", description="Decreases target's natural mana rate by 75%.", school=2, icon_Id=100668288, category=98, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4491, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=52, caster_Effect=0, target_Effect=40, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5068, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=5 /* ManaRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4492;
insert into ace_world.spell set id=4492, name="Incantation of Mana Depletion Self", description="Decreases caster's natural mana rate by 75%.", school=2, icon_Id=100668288, category=98, bitfield=154 /* PKSensitive, SelfTargeted, Reversed, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4492, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=12, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=40, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5070, non_Component_Target_Type=16, mana_Mod=0, duration=300, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=5 /* ManaRate */, stat_Mod_Val=0.25;

delete from ace_world.spell where id=4493;
insert into ace_world.spell set id=4493, name="Incantation of Mana Renewal Other", description="Increases the target's natural mana rate by 145%.", school=2, icon_Id=100668288, category=97, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4493, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=51, caster_Effect=0, target_Effect=39, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5076, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=5 /* ManaRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4494;
insert into ace_world.spell set id=4494, name="Incantation of Mana Renewal Self", description="Increases the caster's natural mana rate by 145%.", school=2, icon_Id=100668288, category=97, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4494, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=39, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5078, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=5 /* ManaRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4495;
insert into ace_world.spell set id=4495, name="Incantation of Regeneration Other", description="Increase target's natural healing rate by 145%.", school=2, icon_Id=100668279, category=93, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4495, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=51, caster_Effect=0, target_Effect=37, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5212, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=3 /* HealthRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4496;
insert into ace_world.spell set id=4496, name="Incantation of Regeneration Self", description="Increase caster's natural healing rate by 145%.", school=2, icon_Id=100668279, category=93, bitfield=16526 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=5, range_Mod=1, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4496, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=37, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5214, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=3 /* HealthRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4497;
insert into ace_world.spell set id=4497, name="Incantation of Rejuvenation Other", description="Increases the rate at which the target regains Stamina by 145%.", school=2, icon_Id=100668299, category=95, bitfield=132 /* Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.25, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4497, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=51, caster_Effect=0, target_Effect=41, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5216, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=20488 /* Float, SingleStat, Multiplicative */, stat_Mod_Key=4 /* StaminaRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4498;
insert into ace_world.spell set id=4498, name="Incantation of Rejuvenation Self", description="Increases the rate at which the caster regains Stamina by 145%.", school=2, icon_Id=100668299, category=95, bitfield=16524 /* Beneficial, SelfTargeted, NotResearchable, FastCast */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=4498, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=11, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=41, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5218, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=4 /* StaminaRate */, stat_Mod_Val=2.45;

delete from ace_world.spell where id=4643;
insert into ace_world.spell set id=4643, name="Incantation of Drain Health Other", description="Drains 60% of the target's Health and gives 35% of it to the caster.", school=2, icon_Id=100668337, category=87, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=68, range_Constant=35, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.85, meta_Spell_Type=4, meta_Spell_Id=4643, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=10, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=32, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4700, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=2 /* Health */, proportion=0.6, loss_Percent=0.65, transfer_Cap=200, transfer_Bitfield=6 /* TargetSource, CasterDestination */;

delete from ace_world.spell where id=4644;
insert into ace_world.spell set id=4644, name="Incantation of Drain Mana Other", description="Drains 60% of the target's Mana and gives it to the caster.", school=2, icon_Id=100668288, category=91, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=68, range_Constant=35, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.85, meta_Spell_Type=4, meta_Spell_Id=4644, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=10, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=34, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4702, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=6 /* Mana */, proportion=0.6, loss_Percent=0, transfer_Cap=200, transfer_Bitfield=6 /* TargetSource, CasterDestination */;

delete from ace_world.spell where id=4645;
insert into ace_world.spell set id=4645, name="Incantation of Drain Stamina Other", description="Drains 60% of the target's Stamina and gives it to the caster.", school=2, icon_Id=100668299, category=89, bitfield=147 /* Resistable, PKSensitive, Reversed, NotResearchable */, mana=68, range_Constant=35, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.85, meta_Spell_Type=4, meta_Spell_Id=4645, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=10, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=36, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4704, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=4 /* Stamina */, proportion=0.6, loss_Percent=0, transfer_Cap=200, transfer_Bitfield=6 /* TargetSource, CasterDestination */;

delete from ace_world.spell where id=4646;
insert into ace_world.spell set id=4646, name="Incantation of Health to Mana Other", description="Drains one-half of the target's Health and gives 200% of that to his/her Mana.", school=2, icon_Id=100668338, category=87, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4646, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=26, spell_Formula_Comp_4_Component_Id=28, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=74, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4872, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=6 /* Mana */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4647;
insert into ace_world.spell set id=4647, name="Incantation of Health to Mana Self", description="Drains one-half of the caster's Health and gives 200% of that to his/her Mana.", school=2, icon_Id=100668338, category=87, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4647, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=74, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4874, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=6 /* Mana */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

delete from ace_world.spell where id=4648;
insert into ace_world.spell set id=4648, name="Incantation of Health to Stamina Other", description="Drains one-half of the target's Health and gives 200% of that to his/her Stamina.", school=2, icon_Id=100668339, category=87, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4648, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=25, spell_Formula_Comp_4_Component_Id=26, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=73, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4876, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=4 /* Stamina */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4649;
insert into ace_world.spell set id=4649, name="Incantation of Health to Stamina Self", description="Drains one-half of the caster's Health and gives 200% of that to his/her Stamina.", school=2, icon_Id=100668339, category=87, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4649, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=73, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4878, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=4 /* Stamina */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

delete from ace_world.spell where id=4650;
insert into ace_world.spell set id=4650, name="Incantation of Infuse Health Other", description="Drains one-quarter of the caster's Health and gives 200% of that to the target.", school=2, icon_Id=100668337, category=88, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.1, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.75, meta_Spell_Type=4, meta_Spell_Id=4650, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=31, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4900, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=2 /* Health */, destination=2 /* Health */, proportion=0.25, loss_Percent=-1, transfer_Bitfield=9 /* CasterSource, TargetDestination */;

delete from ace_world.spell where id=4651;
insert into ace_world.spell set id=4651, name="Incantation of Infuse Mana Other", description="Drains one-quarter of the caster's Mana and gives 200% of that to the target.", school=2, icon_Id=100668288, category=92, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.1, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.75, meta_Spell_Type=4, meta_Spell_Id=4651, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=42, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=33, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4902, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=6 /* Mana */, proportion=0.25, loss_Percent=-1, transfer_Bitfield=9 /* CasterSource, TargetDestination */;

delete from ace_world.spell where id=4652;
insert into ace_world.spell set id=4652, name="Incantation of Infuse Stamina Other", description="Drains one-quarter of the caster's Stamina and gives 200% of that to the target.", school=2, icon_Id=100668299, category=90, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=5, range_Mod=0.1, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.75, meta_Spell_Type=4, meta_Spell_Id=4652, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=53, caster_Effect=0, target_Effect=35, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4904, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=4 /* Stamina */, proportion=0.25, loss_Percent=-1, transfer_Bitfield=9 /* CasterSource, TargetDestination */;

delete from ace_world.spell where id=4653;
insert into ace_world.spell set id=4653, name="Incantation of Mana to Health Other", description="Drains one-half of the target's Mana and gives 200% of that to his/her Health.", school=2, icon_Id=100668341, category=91, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4653, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=26, spell_Formula_Comp_4_Component_Id=34, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=77, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5080, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=2 /* Health */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4654;
insert into ace_world.spell set id=4654, name="Incantation of Mana to Health Self", description="Drains one-half of the caster's Mana and gives 200% of that to his/her Health.", school=2, icon_Id=100668341, category=91, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4654, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=77, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5082, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=2 /* Health */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

delete from ace_world.spell where id=4655;
insert into ace_world.spell set id=4655, name="Incantation of Mana to Stamina Other", description="Drains one-half of the target's Mana and gives 200% of that to his/her stamina.", school=2, icon_Id=100668342, category=91, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4655, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=26, spell_Formula_Comp_4_Component_Id=27, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=78, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5084, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=6 /* Mana */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4656;
insert into ace_world.spell set id=4656, name="Incantation of Mana to Stamina Self", description="Drains one-half of the caster's Mana and gives 200% of that to his/her Stamina.", school=2, icon_Id=100668342, category=91, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4656, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=38, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=78, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5086, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=6 /* Mana */, destination=4 /* Stamina */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

delete from ace_world.spell where id=4657;
insert into ace_world.spell set id=4657, name="Incantation of Stamina to Health Other", description="Drains one-half of the target's Stamina and gives 200% of that to his/her Health.", school=2, icon_Id=100668350, category=89, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4657, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=26, spell_Formula_Comp_4_Component_Id=30, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=75, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5256, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=2 /* Health */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4658;
insert into ace_world.spell set id=4658, name="Incantation of Stamina to Health Self", description="Drains one-half of the caster's Stamina and gives 200% of that to his/her Health.", school=2, icon_Id=100668350, category=89, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4658, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=75, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5258, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=2 /* Health */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

delete from ace_world.spell where id=4659;
insert into ace_world.spell set id=4659, name="Incantation of Stamina to Mana Other", description="Drains one-half of the target's Stamina and gives 200% of that to his/her Mana.", school=2, icon_Id=100668351, category=89, bitfield=130 /* PKSensitive, NotResearchable */, mana=80, range_Constant=5, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4659, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=24, spell_Formula_Comp_3_Component_Id=26, spell_Formula_Comp_4_Component_Id=35, spell_Formula_Comp_5_Component_Id=53, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=76, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5260, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=6 /* Mana */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=10 /* TargetSource, TargetDestination */;

delete from ace_world.spell where id=4981;
insert into ace_world.spell set id=4981, name="Incantation of Stamina to Mana Self", description="Drains one-half of the caster's Stamina and gives 200% of that to his/her Mana.", school=2, icon_Id=100668351, category=89, bitfield=142 /* PKSensitive, Beneficial, SelfTargeted, NotResearchable */, mana=80, range_Constant=0, range_Mod=0, power=400, economy_Mod=0, formula_Version=1, component_Loss=0.15, meta_Spell_Type=4, meta_Spell_Id=4981, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=9, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=26, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=61, caster_Effect=0, target_Effect=76, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5262, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, source=4 /* Stamina */, destination=6 /* Mana */, proportion=0.5, loss_Percent=-1, transfer_Bitfield=5 /* CasterSource, CasterDestination */;

