/* war magic 8 */

delete from ace_world.spell where id=4421;
insert into ace_world.spell set id=4421, name="Incantation of Acid Arc", description="Shoots a stream of acid at the target. The stream does 142-204 points of acid damage to the first thing it hits.", school=1, icon_Id=100673315, category=117, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4421, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4510, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=32 /* Acid */, base_Intensity=142, variance=62, wcid=20973, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4422;
insert into ace_world.spell set id=4422, name="Incantation of Blade Arc", description="Shoots a magical blade at the target. The bolt does 142-204 points of slashing damage to the first thing it hits.", school=1, icon_Id=100673316, category=123, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4422, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4574, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=1 /* Slash */, base_Intensity=142, variance=62, wcid=20979, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4423;
insert into ace_world.spell set id=4423, name="Incantation of Flame Arc", description="Shoots a bolt of flame at the target.  The bolt does 142-204 points of fire damage to the first thing it hits.", school=1, icon_Id=100673318, category=121, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4423, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4758, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=16 /* Fire */, base_Intensity=142, variance=62, wcid=20974, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4424;
insert into ace_world.spell set id=4424, name="Incantation of Force Arc", description="Shoots a bolt of force at the target. The bolt does 142-204 points of piercing damage to the first thing it hits.", school=1, icon_Id=100673319, category=122, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4424, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4784, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=2 /* Pierce */, base_Intensity=142, variance=62, wcid=20975, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4425;
insert into ace_world.spell set id=4425, name="Incantation of Frost Arc", description="Shoots a bolt of cold at the target. The bolt does 142-204 points of cold damage to the first thing it hits.", school=1, icon_Id=100673320, category=119, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4425, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4798, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=8 /* Cold */, base_Intensity=142, variance=62, wcid=20976, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4426;
insert into ace_world.spell set id=4426, name="Incantation of Lightning Arc", description="Shoots a bolt of lighting at the target. The bolt does 142-204 points of electrical damage to the first thing it hits.", school=1, icon_Id=100673321, category=120, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4426, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5004, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=64 /* Electric */, base_Intensity=142, variance=62, wcid=20977, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4427;
insert into ace_world.spell set id=4427, name="Incantation of Shock Arc", description="Shoots a shock wave at the target. The wave does 142-204 points of bludgeoning damage to the first thing it hits.", school=1, icon_Id=100673317, category=118, bitfield=4227 /* Resistable, PKSensitive, NotResearchable, NonTrackingProjectile */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4427, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5232, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=4 /* Bludgeon */, base_Intensity=142, variance=62, wcid=20978, num_Projectiles=1, non_Tracking=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4431;
insert into ace_world.spell set id=4431, name="Incantation of Acid Blast", description="Shoots five streams of acid outward from the caster. Each stream does 47-94 points of acid damage to the first thing it hits.", school=1, icon_Id=100668335, category=131, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4431, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4514, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=32 /* Acid */, base_Intensity=47, variance=47, wcid=1633, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4432;
insert into ace_world.spell set id=4432, name="Incantation of Acid Streak", description="Sends a stream of acid streaking towards the target. The stream does 47-94 points of acid damage to the first thing it hits.", school=1, icon_Id=100670698, category=243, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4432, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4522, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=32 /* Acid */, base_Intensity=47, variance=47, wcid=7262, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4433;
insert into ace_world.spell set id=4433, name="Incantation of Acid Stream", description="Shoots a stream of acid at the target. The stream does 142-204 points of acid damage to the first thing it hits.", school=1, icon_Id=100668334, category=117, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4433, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4524, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=32 /* Acid */, base_Intensity=142, variance=62, wcid=1633, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4434;
insert into ace_world.spell set id=4434, name="Incantation of Acid Volley", description="Shoots five streams of acid toward the target. Each stream does 47-94 points of acid damage to the first thing it hits.", school=1, icon_Id=100668335, category=207, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4434, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=37, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4530, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=32 /* Acid */, base_Intensity=47, variance=47, wcid=1633, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4435;
insert into ace_world.spell set id=4435, name="Incantation of Blade Blast", description="Shoots five whirling blades outward from the caster. Each blade does 47-94 points of slashing damage to the first thing it hits.", school=1, icon_Id=100669738, category=137, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4435, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4578, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=1 /* Slash */, base_Intensity=47, variance=47, wcid=1636, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4436;
insert into ace_world.spell set id=4436, name="Incantation of Blade Volley", description="Shoots five whirling blades toward the target. Each blade does 47-94 points of Slashing damage to the first thing it hits.", school=1, icon_Id=100669738, category=213, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4436, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4586, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=1 /* Slash */, base_Intensity=47, variance=47, wcid=1636, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4437;
insert into ace_world.spell set id=4437, name="Incantation of Bludgeoning Volley", description="Shoots five shock waves toward the target. Each wave does 47-94 points of bludgeoning damage to the first thing it hits.", school=1, icon_Id=100669737, category=208, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4437, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4636, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=4 /* Bludgeon */, base_Intensity=47, variance=47, wcid=1634, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4438;
insert into ace_world.spell set id=4438, name="Incantation of Flame Blast", description="Shoots five bolts of flame outward from the caster. Each bolt does 47-94 points of fire damage to the first thing it hits.", school=1, icon_Id=100668275, category=135, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4438, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4762, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=16 /* Fire */, base_Intensity=47, variance=47, wcid=1499, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4439;
insert into ace_world.spell set id=4439, name="Incantation of Flame Bolt", description="Shoots a bolt of flame at the target.  The bolt does 142-204 points of fire damage to the first thing it hits.", school=1, icon_Id=100668276, category=121, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4439, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4764, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=16 /* Fire */, base_Intensity=142, variance=62, wcid=1499, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4440;
insert into ace_world.spell set id=4440, name="Incantation of Flame Streak", description="Sends a bolt of flame streaking towards the target.  The bolt does 47-94 points of fire damage to the first thing it hits.", school=1, icon_Id=100670706, category=247, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4440, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4768, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=16 /* Fire */, base_Intensity=47, variance=47, wcid=7263, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4441;
insert into ace_world.spell set id=4441, name="Incantation of Flame Volley", description="Shoots five bolts of flame toward the target. Each bolt does 47-94 points of fire damage to the first thing it hits.", school=1, icon_Id=100668275, category=211, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=15, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4441, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=69, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4770, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=16 /* Fire */, base_Intensity=47, variance=47, wcid=1499, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4442;
insert into ace_world.spell set id=4442, name="Incantation of Force Blast", description="Shoots five force bolts outward from the caster. Each bolt does 47-94 points of piercing damage to the first thing it hits.", school=1, icon_Id=100669739, category=136, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4442, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4786, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=2 /* Pierce */, base_Intensity=47, variance=47, wcid=1667, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4443;
insert into ace_world.spell set id=4443, name="Incantation of Force Bolt", description="Shoots a bolt of force at the target. The bolt does 142-204 points of piercing damage to the first thing it hits.", school=1, icon_Id=100668343, category=122, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4443, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4788, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=2 /* Pierce */, base_Intensity=142, variance=62, wcid=1667, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4444;
insert into ace_world.spell set id=4444, name="Incantation of Force Streak", description="Sends a bolt of force streaking towards the target. The bolt does 47-94 points of piercing damage to the first thing it hits.", school=1, icon_Id=100670718, category=248, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4444, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4790, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=2 /* Pierce */, base_Intensity=47, variance=47, wcid=7264, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4445;
insert into ace_world.spell set id=4445, name="Incantation of Force Volley", description="Shoots five bolts of force toward the target. Each bolt does 47-94 points of piercing damage to the first thing it hits.", school=1, icon_Id=100669739, category=212, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.4, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4445, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=44, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4792, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=2 /* Pierce */, base_Intensity=47, variance=47, wcid=1667, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4446;
insert into ace_world.spell set id=4446, name="Incantation of Frost Blast", description="Shoots five bolts of frost outward from the caster. Each bolt does 47-94 points of cold damage to the first thing it hits.", school=1, icon_Id=100668280, category=133, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4446, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4802, non_Component_Target_Type=0, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=8 /* Cold */, base_Intensity=47, variance=47, wcid=1503, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4447;
insert into ace_world.spell set id=4447, name="Incantation of Frost Bolt", description="Shoots a bolt of cold at the target. The bolt does 142-204 points of cold damage to the first thing it hits.", school=1, icon_Id=100668281, category=119, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4447, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4804, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=8 /* Cold */, base_Intensity=142, variance=62, wcid=1503, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4448;
insert into ace_world.spell set id=4448, name="Incantation of Frost Streak", description="Sends a bolt of cold streaking towards the target. The bolt does 47-94 points of cold damage to the first thing it hits.", school=1, icon_Id=100670710, category=245, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4448, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4808, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=8 /* Cold */, base_Intensity=47, variance=47, wcid=7265, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4449;
insert into ace_world.spell set id=4449, name="Incantation of Frost Volley", description="Shoots five bolts of frost toward the target. Each bolt does 47-94 points of cold damage to the first thing it hits.", school=1, icon_Id=100668280, category=209, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4449, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=41, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=4810, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=8 /* Cold */, base_Intensity=47, variance=47, wcid=1503, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4450;
insert into ace_world.spell set id=4450, name="Incantation of Lightning Blast", description="Shoots five bolts of lightning outward from the caster. Each bolt does 47-94 points of electric damage to the first thing it hits.", school=1, icon_Id=100668340, category=134, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4450, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5010, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=64 /* Electric */, base_Intensity=47, variance=47, wcid=1635, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4451;
insert into ace_world.spell set id=4451, name="Incantation of Lightning Bolt", description="Shoots a bolt of lighting at the target. The bolt does 142-204 points of electrical damage to the first thing it hits.", school=1, icon_Id=100668333, category=120, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4451, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5012, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=64 /* Electric */, base_Intensity=142, variance=62, wcid=1635, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4452;
insert into ace_world.spell set id=4452, name="Incantation of Lightning Streak", description="Sends a bolt of lighting streaking towards the target. The bolt does 47-94 points of electrical damage to the first thing it hits.", school=1, icon_Id=100670714, category=246, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4452, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5022, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=64 /* Electric */, base_Intensity=47, variance=47, wcid=7266, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4453;
insert into ace_world.spell set id=4453, name="Incantation of Lightning Volley", description="Shoots five bolts of lightning toward the target. Each bolt does 47-94 points of electric damage to the first thing it hits.", school=1, icon_Id=100668340, category=210, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4453, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=40, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5024, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=64 /* Electric */, base_Intensity=47, variance=47, wcid=1635, num_Projectiles=5, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4454;
insert into ace_world.spell set id=4454, name="Incantation of Shock Blast", description="Shoots five shock waves outward from the caster. Each wave does 47-94 points of damage to the first thing it hits.", school=1, icon_Id=100669737, category=132, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4454, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=17, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=70, spell_Formula_Comp_8_Component_Id=56, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5234, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=4 /* Bludgeon */, base_Intensity=47, variance=47, wcid=1634, num_Projectiles=5, spread_Angle=90, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=5, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4455;
insert into ace_world.spell set id=4455, name="Incantation of Shock Wave", description="Shoots a shock wave at the target. The wave does 142-204 points of bludgeoning damage to the first thing it hits.", school=1, icon_Id=100668336, category=118, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4455, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5236, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=4 /* Bludgeon */, base_Intensity=142, variance=62, wcid=1634, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4456;
insert into ace_world.spell set id=4456, name="Incantation of Shock Wave Streak", description="Sends a shock wave streaking towards the target. The wave does 47-94 points of bludgeoning damage to the first thing it hits.", school=1, icon_Id=100670702, category=244, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4456, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=67, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5238, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=4 /* Bludgeon */, base_Intensity=47, variance=47, wcid=7267, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4457;
insert into ace_world.spell set id=4457, name="Incantation of Whirling Blade", description="Shoots a magical blade at the target. The bolt does 142-204 points of slashing damage to the first thing it hits.", school=1, icon_Id=100668349, category=123, bitfield=131 /* Resistable, PKSensitive, NotResearchable */, mana=40, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4457, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=15, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5322, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=204, e_Type=1 /* Slash */, base_Intensity=142, variance=62, wcid=1636, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;

delete from ace_world.spell where id=4458;
insert into ace_world.spell set id=4458, name="Incantation of Whirling Blade Streak", description="Sends a magical blade streaking towards the target. The bolt does 47-94 points of slashing damage to the first thing it hits.", school=1, icon_Id=100670722, category=249, bitfield=16515 /* Resistable, PKSensitive, NotResearchable, FastCast */, mana=80, range_Constant=30, range_Mod=0.2, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=2, meta_Spell_Id=4458, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=18, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=34, spell_Formula_Comp_6_Component_Id=47, spell_Formula_Comp_7_Component_Id=65, spell_Formula_Comp_8_Component_Id=55, caster_Effect=0, target_Effect=0, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=5324, non_Component_Target_Type=16, mana_Mod=0, duration=0, degrade_Modifier=0, degrade_Limit=0, stat_Mod_Val=94, e_Type=1 /* Slash */, base_Intensity=47, variance=47, wcid=7268, num_Projectiles=1, padding_Origin_X=1, padding_Origin_Y=1, padding_Origin_Z=1, dims_Origin_X=1, dims_Origin_Y=1, dims_Origin_Z=1;
