delete from ace_world.spell where id=5982;
insert into ace_world.spell set id=5982, name="Aura of Hermetic Link Other I", description="Increases a magic casting implement's mana conversion bonus by 10%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=25, economy_Mod=1, formula_Version=1, component_Loss=0.01, meta_Spell_Type=1, meta_Spell_Id=5982, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=8, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=39, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=784, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.1;

delete from ace_world.spell where id=5983;
insert into ace_world.spell set id=5983, name="Aura of Hermetic Link Other II", description="Increases a magic casting implement's mana conversion bonus by 20%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=5983, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=69, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=39, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=786, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.2;

delete from ace_world.spell where id=5984;
insert into ace_world.spell set id=5984, name="Aura of Hermetic Link Other III", description="Increases a magic casting implement's mana conversion bonus by 30%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=5984, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=70, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=788, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.3;

delete from ace_world.spell where id=5985;
insert into ace_world.spell set id=5985, name="Aura of Hermetic Link Other IV", description="Increases a magic casting implement's mana conversion bonus by 40%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5985, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=790, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.4;

delete from ace_world.spell where id=5986;
insert into ace_world.spell set id=5986, name="Aura of Hermetic Link Other V", description="Increases a magic casting implement's mana conversion bonus by 50%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=5986, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=66, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=792, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.5;

delete from ace_world.spell where id=5987;
insert into ace_world.spell set id=5987, name="Aura of Hermetic Link Other VI", description="Increases a magic casting implement's mana conversion bonus by 60%.", school=3, icon_Id=100673984, category=195, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=5987, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=794, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.6;

delete from ace_world.spell where id=5988;
insert into ace_world.spell set id=5988, name="Aura of Hermetic Link Other VII", description="Increases a magic casting implement's mana conversion bonus by 70%.", school=3, icon_Id=100673984, category=195, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5988, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=8, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=39, spell_Formula_Comp_7_Component_Id=68, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=67, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=795, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33574920 /* Float, SingleStat, Multiplicative, Beneficial */, stat_Mod_Key=171 /* WeaponAuraManaConv */, stat_Mod_Val=1.7;

delete from ace_world.spell where id=5990;
insert into ace_world.spell set id=5990, name="Aura of Blood Drinker Other I", description="Increases a weapon's damage value by 2 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=1, economy_Mod=1, formula_Version=1, component_Loss=0, meta_Spell_Type=1, meta_Spell_Id=5990, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=43, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=712, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=2;

delete from ace_world.spell where id=5991;
insert into ace_world.spell set id=5991, name="Aura of Blood Drinker Other II", description="Increases a weapon's damage value by 4 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=5991, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=43, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=714, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=4;

delete from ace_world.spell where id=5992;
insert into ace_world.spell set id=5992, name="Aura of Blood Drinker Other III", description="Increases a weapon's damage value by 8 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=5992, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=716, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=8;

delete from ace_world.spell where id=5993;
insert into ace_world.spell set id=5993, name="Aura of Blood Drinker Other IV", description="Increases a weapon's damage value by 12 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5993, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=718, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=12;

delete from ace_world.spell where id=5994;
insert into ace_world.spell set id=5994, name="Aura of Blood Drinker Other V", description="Increases a weapon's damage value by 16 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=5994, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=720, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=16;

delete from ace_world.spell where id=5995;
insert into ace_world.spell set id=5995, name="Aura of Blood Drinker Other VI", description="Increases a weapon's damage value by 20 points.", school=3, icon_Id=100673986, category=154, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=5995, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=722, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=20;

delete from ace_world.spell where id=5996;
insert into ace_world.spell set id=5996, name="Aura of Blood Drinker Other VII", description="Increases a weapon's damage value by 22 points.", school=3, icon_Id=100673986, category=154, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5996, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=723, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=22;

delete from ace_world.spell where id=5997;
insert into ace_world.spell set id=5997, name="Aura of Incantation of Blood Drinker Other", description="Increases a weapon's damage value by 24 points.", school=3, icon_Id=100673986, category=154, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=80, range_Constant=25, range_Mod=0, power=400, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=5997, spell_Formula_Comp_1_Component_Id=193, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=812, non_Component_Target_Type=16, mana_Mod=0, duration=5400, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=360 /* WeaponAuraDamage */, stat_Mod_Val=24;

delete from ace_world.spell where id=5999;
insert into ace_world.spell set id=5999, name="Aura of Defender Other I", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 3%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=1, economy_Mod=1, formula_Version=1, component_Loss=0.01, meta_Spell_Type=1, meta_Spell_Id=5999, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=46, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=736, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.03;

delete from ace_world.spell where id=6000;
insert into ace_world.spell set id=6000, name="Aura of Defender Other II", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 5%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=6000, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=46, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=738, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.05;

delete from ace_world.spell where id=6001;
insert into ace_world.spell set id=6001, name="Aura of Defender Other III", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 7.5%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=6001, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=740, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.05;

delete from ace_world.spell where id=6002;
insert into ace_world.spell set id=6002, name="Aura of Defender Other IV", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 10%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6002, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=742, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.1;

delete from ace_world.spell where id=6003;
insert into ace_world.spell set id=6003, name="Aura of Defender Other V", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 13%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=6003, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=74, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=744, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.13;

delete from ace_world.spell where id=6004;
insert into ace_world.spell set id=6004, name="Aura of Defender Other VI", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 15%.", school=3, icon_Id=100673988, category=156, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=6004, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=746, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.15;

delete from ace_world.spell where id=6005;
insert into ace_world.spell set id=6005, name="Aura of Defender Other VII", description="Increases the Melee Defense skill modifier of a weapon or magic caster by 17%.", school=3, icon_Id=100673988, category=156, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6005, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=63, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=46, spell_Formula_Comp_7_Component_Id=74, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=61, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=747, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=169 /* WeaponAuraDefense */, stat_Mod_Val=0.17;

delete from ace_world.spell where id=6007;
insert into ace_world.spell set id=6007, name="Aura of Heart Seeker Other I", description="Increases a weapon's Attack Skill modifier by 2.5 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=1, economy_Mod=1, formula_Version=1, component_Loss=0.01, meta_Spell_Type=1, meta_Spell_Id=6007, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=48, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=760, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=2.5;

delete from ace_world.spell where id=6008;
insert into ace_world.spell set id=6008, name="Aura of Heart Seeker Other II", description="Increases a weapon's Attack Skill modifier by 5.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=6008, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=48, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=762, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=5;

delete from ace_world.spell where id=6009;
insert into ace_world.spell set id=6009, name="Aura of Heart Seeker Other III", description="Increases a weapon's Attack Skill modifier by 7.5 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=6009, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=64, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=764, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=7.5;

delete from ace_world.spell where id=6010;
insert into ace_world.spell set id=6010, name="Aura of Heart Seeker Other IV", description="Increases a weapon's Attack Skill modifier by 10.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6010, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=66, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=65, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=766, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=10;

delete from ace_world.spell where id=6011;
insert into ace_world.spell set id=6011, name="Aura of Heart Seeker Other V", description="Increases a weapon's Attack Skill modifier by 12.5 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=6011, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=67, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=63, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=768, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=12.5;

delete from ace_world.spell where id=6012;
insert into ace_world.spell set id=6012, name="Aura of Heart Seeker Other VI", description="Increases a weapon's Attack Skill modifier by 15.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=6012, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=770, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=15;

delete from ace_world.spell where id=6013;
insert into ace_world.spell set id=6013, name="Aura of Heart Seeker Other VII", description="Increases a weapon's Attack Skill modifier by 17.0 percentage points.", school=3, icon_Id=100673989, category=152, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6013, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=68, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=67, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=48, spell_Formula_Comp_7_Component_Id=64, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=59, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=771, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=168 /* WeaponAuraOffense */, stat_Mod_Val=17;

delete from ace_world.spell where id=6015;
insert into ace_world.spell set id=6015, name="Aura of Spirit Drinker Other I", description="Increases the elemental damage bonus of an elemental magic caster by 1%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=1, economy_Mod=1, formula_Version=1, component_Loss=0, meta_Spell_Type=1, meta_Spell_Id=6015, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=43, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=850, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.01;

delete from ace_world.spell where id=6016;
insert into ace_world.spell set id=6016, name="Aura of Spirit Drinker Other II", description="Increases the elemental damage bonus of an elemental magic caster by 2%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=6016, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=71, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=43, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=852, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.02;

delete from ace_world.spell where id=6017;
insert into ace_world.spell set id=6017, name="Aura of Spirit Drinker Other III", description="Increases the elemental damage bonus of an elemental magic caster by 3%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=6017, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=72, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=66, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=854, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.03;

delete from ace_world.spell where id=6018;
insert into ace_world.spell set id=6018, name="Aura of Spirit Drinker Other IV", description="Increases the elemental damage bonus of an elemental magic caster by 4%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6018, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=68, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=856, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.04;

delete from ace_world.spell where id=6019;
insert into ace_world.spell set id=6019, name="Aura of Spirit Drinker Other V", description="Increases the elemental damage bonus of an elemental magic caster by 5%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=6019, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=69, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=71, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=858, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.05;

delete from ace_world.spell where id=6020;
insert into ace_world.spell set id=6020, name="Aura of Spirit Drinker Other VI", description="Increases the elemental damage bonus of an elemental magic caster by 6%.", school=3, icon_Id=100676645, category=695, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=6020, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=860, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.06;

delete from ace_world.spell where id=6021;
insert into ace_world.spell set id=6021, name="Aura of Spirit Drinker Other VII", description="Increases the elemental damage bonus of an elemental magic caster by 7%.", school=3, icon_Id=100676645, category=695, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6021, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=43, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=57, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=861, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591304 /* Float, SingleStat, Additive, Beneficial */, stat_Mod_Key=170 /* WeaponAuraElemental */, stat_Mod_Val=0.07;

delete from ace_world.spell where id=6024;
insert into ace_world.spell set id=6024, name="Aura of Swift Killer Other I", description="Improves a weapon's speed by 10 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=10, range_Constant=25, range_Mod=0, power=1, economy_Mod=1, formula_Version=1, component_Loss=0, meta_Spell_Type=1, meta_Spell_Id=6024, spell_Formula_Comp_1_Component_Id=1, spell_Formula_Comp_2_Component_Id=7, spell_Formula_Comp_3_Component_Id=36, spell_Formula_Comp_4_Component_Id=45, spell_Formula_Comp_5_Component_Id=49, spell_Formula_Comp_6_Component_Id=0, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=874, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-10;

delete from ace_world.spell where id=6025;
insert into ace_world.spell set id=6025, name="Aura of Swift Killer Other II", description="Improves a weapon's speed by 20 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=20, range_Constant=25, range_Mod=0, power=50, economy_Mod=1, formula_Version=1, component_Loss=0.05, meta_Spell_Type=1, meta_Spell_Id=6025, spell_Formula_Comp_1_Component_Id=2, spell_Formula_Comp_2_Component_Id=73, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=36, spell_Formula_Comp_5_Component_Id=45, spell_Formula_Comp_6_Component_Id=49, spell_Formula_Comp_7_Component_Id=0, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=876, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-20;

delete from ace_world.spell where id=6026;
insert into ace_world.spell set id=6026, name="Aura of Swift Killer Other III", description="Improves a weapon's speed by 30 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=30, range_Constant=25, range_Mod=0, power=100, economy_Mod=1, formula_Version=1, component_Loss=0.1, meta_Spell_Type=1, meta_Spell_Id=6026, spell_Formula_Comp_1_Component_Id=3, spell_Formula_Comp_2_Component_Id=74, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=70, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=878, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-30;

delete from ace_world.spell where id=6027;
insert into ace_world.spell set id=6027, name="Aura of Swift Killer Other IV", description="Improves a weapon's speed by 40 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=40, range_Constant=25, range_Mod=0, power=150, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6027, spell_Formula_Comp_1_Component_Id=4, spell_Formula_Comp_2_Component_Id=63, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=71, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=49, spell_Formula_Comp_8_Component_Id=0, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=880, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-40;

delete from ace_world.spell where id=6028;
insert into ace_world.spell set id=6028, name="Aura of Swift Killer Other V", description="Improves a weapon's speed by 50 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=50, range_Constant=25, range_Mod=0, power=200, economy_Mod=1, formula_Version=1, component_Loss=0.2, meta_Spell_Type=1, meta_Spell_Id=6028, spell_Formula_Comp_1_Component_Id=5, spell_Formula_Comp_2_Component_Id=64, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=72, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=72, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=882, non_Component_Target_Type=16, mana_Mod=0, duration=1800, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-50;

delete from ace_world.spell where id=6029;
insert into ace_world.spell set id=6029, name="Aura of Swift Killer Other VI", description="Improves a weapon's speed by 60 points.", school=3, icon_Id=100673991, category=158, bitfield=6 /* PKSensitive, Beneficial */, mana=60, range_Constant=25, range_Mod=0, power=250, economy_Mod=1, formula_Version=1, component_Loss=0.3, meta_Spell_Type=1, meta_Spell_Id=6029, spell_Formula_Comp_1_Component_Id=6, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=884, non_Component_Target_Type=16, mana_Mod=0, duration=2700, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-60;

delete from ace_world.spell where id=6030;
insert into ace_world.spell set id=6030, name="Aura of Swift Killer Other VII", description="Improves a weapon's speed by 70 points.", school=3, icon_Id=100673991, category=158, bitfield=134 /* PKSensitive, Beneficial, NotResearchable */, mana=70, range_Constant=25, range_Mod=0, power=300, economy_Mod=1, formula_Version=1, component_Loss=0.15, meta_Spell_Type=1, meta_Spell_Id=6030, spell_Formula_Comp_1_Component_Id=112, spell_Formula_Comp_2_Component_Id=65, spell_Formula_Comp_3_Component_Id=7, spell_Formula_Comp_4_Component_Id=73, spell_Formula_Comp_5_Component_Id=36, spell_Formula_Comp_6_Component_Id=45, spell_Formula_Comp_7_Component_Id=73, spell_Formula_Comp_8_Component_Id=49, caster_Effect=0, target_Effect=63, fizzle_Effect=0, recovery_Interval=0, recovery_Amount=0, display_Order=885, non_Component_Target_Type=16, mana_Mod=0, duration=3600, degrade_Modifier=0, degrade_Limit=-666, stat_Mod_Type=33591300 /* Int, SingleStat, Additive, Beneficial */, stat_Mod_Key=361 /* WeaponAuraSpeed */, stat_Mod_Val=-70;