DELETE FROM `weenie` WHERE `class_Id` = 72799;

INSERT INTO `weenie` (`class_Id`, `class_Name`, `type`, `last_Modified`)
VALUES (72799, 'ace72799-thesistersoflight', 8, '2022-01-08 18:29:57') /* Book */;

INSERT INTO `weenie_properties_int` (`object_Id`, `type`, `value`)
VALUES (72799,   1,        128) /* ItemType - Misc */
     , (72799,   5,         25) /* EncumbranceVal */
     , (72799,  16,          8) /* ItemUseable - Contained */
     , (72799,  19,         20) /* Value */
     , (72799,  33,          1) /* Bonded - Bonded */
     , (72799,  93,       1044) /* PhysicsState - Ethereal, IgnoreCollisions, Gravity */
     , (72799, 114,          1) /* Attuned - Attuned */;

INSERT INTO `weenie_properties_float` (`object_Id`, `type`, `value`)
VALUES (72799,  54,       1) /* UseRadius */;

INSERT INTO `weenie_properties_string` (`object_Id`, `type`, `value`)
VALUES (72799,   1, 'The Sisters of Light') /* Name */
     , (72799,  16, 'A translation of the book found in the Temple of Mysteries, beneath the Vesayen Isles.') /* LongDesc */;

INSERT INTO `weenie_properties_d_i_d` (`object_Id`, `type`, `value`)
VALUES (72799,   1, 0x02001429) /* Setup */
     , (72799,   3, 0x20000014) /* SoundTable */
     , (72799,   8, 0x060060FC) /* Icon */
     , (72799,  22, 0x3400002B) /* PhysicsEffectTable */;

INSERT INTO `weenie_properties_book` (`object_Id`, `max_Num_Pages`, `max_Num_Chars_Per_Page`)
VALUES (72799, 24, 1000);

INSERT INTO `weenie_properties_book_page_data` (`object_Id`, `page_Id`, `author_Id`, `author_Name`, `author_Account`, `ignore_Author`, `page_Text`)
VALUES (72799, 0, 0xFFFFFFFF, 'Unknown', 'prewritten', False, 'Excerpt from the report of the journals of Lady Kahrienne, Royal Anthropologist assigned to Lady Adja of Ithaenc, Trip 17 into the tribal lands of the Tulith.  ')
     , (72799, 1, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'So after so many years of effort, I am pleased to say that I have finally made progress with the Tulith tribe. Unlike many nomadic tribes, it is interesting that with the Tulith, the positions of power follow the matriarchal lines. When I asked about this, my male chaperon laughed and said, "Because one can never really be sure who fathers a child, but you know beyond a doubt whom the mother is." When I asked him if this meant men were second class citizens, he looked at me with amused look a parent has for an offspring who questions the most basic things in life. He explained that males were equal to females, and just because one leads, it does not make one more valuable than those who follow.  ')
     , (72799, 2, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'What is the point of a shepherd who has no flock to tend? I asked many such questions, though my questions must have endeared me to him, for he obtained an invitation to his great, great aunt''s fire. To my utter delight, I discovered that this great dame was in fact, this band''s grand matriarch and leader. After a simple, but completely satisfying meal, I was treated to one of their greatest oral histories. What follows is the most accurate transcription that I could give, having to write it down after the fact, for to do so during the story would have been considered an insult. I checked the facts with my chaperon and he agreed that my rendition was well scribed.  ')
     , (72799, 3, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, '"So my children it is known that in regards to all things, the Universe strives to maintain balance. So when darkness grew in power in the form of the Three Dark Matriarchs, the Three Light Sisters arose to keep the schemes of evil in check. These three maidens, only children at the time, could no longer bare the suffering of their people. Surely the moons would take pity on their people if given the right tribute. But what could they give the moons, who surely had more than three poor sisters. They decided to offer the moons their lives-to either be their slaves or to forever do the moons'' bidding. An eternity of servitude must be worth something. The girls snuck out of their wagon on the night of the dual full moon and made their way to a hidden oasis. There the sisters sang the most sacred of songs to the moons-songs composed from the purity of their hearts. The moon avatars, touched by the purity of the girls'' innocence and sincerity, agreed to help.  ')
     , (72799, 4, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'But instead of serving the moons in the heavens, in which they could do little, they graced the sisters with the ability to stand against the Matriarchs. They warned the sisters that they must always work in harmony, as they did that night, or their powers would fail.  ')
     , (72799, 5, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'Drawing their powers from the rhythms of nature, each sister had a time of day in which she was the strongest. The first sister was the Lady of Growth and Beginnings, so her time was that of morning and unto her the desert flowers of the oases were sacred, for it was there the mighty aquifers were discovered and used to irrigate the great fields of our ancient empire. And to her the hunt-beasts of the dunes were sacred, obeying her wishes without hesitation.  ')
     , (72799, 6, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'The second sister was known as the Lady of Harvest and Justice, so her time was that of the high sun when all things are made clear for nothing can hide from the all-seeing eye of the Noon Day Sun. To this sister the Bloodroot Vines were sacred, whose sap was used as a truth serum to make the false of tongue speak true. To this sister, the great beasts of the forests were hers to command. The third sister was known as the Lady of Twilight and Rest, so her time was the evening and unto her the Alb''arean Ore was sacred, whose grains could be used for healing as well as a soothing ointment to calm the most ragged of souls. The great beasts of the plains were this sister''s servants.  ')
     , (72799, 7, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'Working in unity and harmony, the Light Sisters were able to fight back the darkness from our lands. After seventeen long years of war, the Dark Matriarchs were defeated and their forces were driven back to the filthy mud swamps they crawled out of. Yet, the Light Sisters knew that their task was just beginning; their society had to be rebuilt after so many years of oppression. The Light Sisters had grown as wise as they were powerful, and each set up a temple of learning to teach what they knew-for knowledge must be shared and spread if it is to thrive. Keeping it clutched to one''s heart is a fool''s hand, for when such a miser dies, the knowledge dies with him. The Light Sisters knew they would not live forever, so the best way to insure their people''s freedom was to have as many Falatacot as possible educated in the Path of Light.  ')
     , (72799, 8, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'Since the Light Sisters'' powers came from balance, their students were required to follow three paths of learning-the magic specific to each sister''s domain, a combat skill (for one must never rely on magic alone) and a healing art (for one must know how to preserve life as well as take it). These temples grew in reputation and helped the cities that grew around them prosper. As generations past, a new ''sister'' was chosen from the bloodlines of the original three to keep the order. The descendants of the original sisters often intermarried in the hopes of producing stronger offspring; to the point that after many generations, there was no longer a separation of the bloodlines. Then an unheard of thing happened-three actual sisters were chosen to inherit the positions.  ')
     , (72799, 9, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'There was much rejoicing from the population who believed this was a great time, for these sisters must be the reincarnation of the first sisters and this must be the beginning of a new age of glory-for the Sisters had returned, and looking at all they had achieved before, only greater things could lay ahead. But in the quiet corridors, the wisest of elders whispered misgiving, for what if these sisters were chosen because a new great evil was growing and the bonds of blood as well as magic would be needed?  ')
     , (72799, 10, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'And they were right. For the Dark Matriarchs, who were the same hags who had fought the original Light Sisters, had seen what was to come. Using the power of the Book of Eibhil, they had seen their downfall by the reincarnation of the Light Sisters-incarnations who were so powerful, they would discover the way to stay young forever.  ')
     , (72799, 11, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'This would give them the time to find the way to bring down the Dark Matriarchs and replace them as the teachers of the powers of the Falatacot that were not bound to the darkness within the world. This the hags would not have. Using the Book to enhance their powers, they created the perfect tool to destroy the Light Sisters. Now, the Dark Matriarchs ruled a society where women controlled all and men were used for procreation, combat and for menial labor. The idea that the Cities of Light believed in equality amongst the sexes sickened them. So they decided to use this obvious weakness against the Light Sisters. The created the most handsome man that had ever walked the land. But that was not all; they gave him the empathic ability to be able to change his personality to become the perfect companion to whatever person he was with.  ')
     , (72799, 12, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'So if he was with a man who wanted an intellectual friend, that is what their creation was. If a lady wanted a humorous man, than that is what their creation became. So through their combined magics, he was brought to life. But life was not enough; their spawn needed to be clever, not just pretty. The hags spent years grooming him for his task to annihilate the Light Sisters the only way they could be destroyed-by destroying themselves. If the Light Sisters did not work in harmony, there would be no magic and a handsome face was the best way to cause discord between three silly sisters. Pleased with their work, the hags named their weapon Sath''tik.  ')
     , (72799, 13, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'Now, there was a fourth sister, who was not seen as necessary in this fight against evil-for there was no counterpart for her to fight. While her elder sisters were groomed from a young age for their roles, the youngest sister was allowed to follow her own interests. What others saw as a scattered focus, her tutors realized was the insatiable thirst of a child prodigy. The youngest sister not only had a flawless memory, she could see things in ways others could not, recognize patterns and connections that were otherwise hidden. She would spend her time throughout any given year visiting her sisters'' temples, as well as other places of learning-mastering in weeks what would take others years. Now while she was away studying with one of the great Deru trees themselves, the ''raids'' began.  ')
     , (72799, 14, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'The forces of the Dark Matriarchs used false raids to get Sath''tik into the Cities of Light, under the guise as a prisoner who was rescued by the Light Falatacot forces. His charm got him introductions to higher and higher ranked individuals, until he finally met the Lady of Growth and Morning, who was sought to heal his wounds. She was enchanted with Sath''tik, as she had to be. Through her, he was able to meet her sisters and one by one he began to seduce them. So great was his powers of enchantment, they all fell hopelessly and blindly in love with him. And these growing loves were the perfect fertile grounds to plant the seeds of jealousy. Every complement had a hidden comparison. Every praise contained a hidden jab. But the sisters were so enchanted, they could not see the truth.  ')
     , (72799, 15, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'All except the youngest sister. From her earliest days, she had been flattered and fawned upon because of her elder siblings-to the point of frustration. Hating the superfluous nature of the courts, it was her dearest wish that people around her would be sincere and truthful. As such, Sath''tik''s true character could not help but come through. The youngest sister saw his false nature, but she could not get her sisters or anyone else to believe her. In one confrontation, the eldest sister expelled the youngest from her temple. The infighting began, and the power of the Light began to diminish. But when one is blinded by the sun, it is hard to see the light dim.  ')
     , (72799, 16, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'The youngest sister fled to her Deru masters to find help. While she was away, Sath''tik arranged his greatest performance. He was found bloodied and near death outside each temple with ''evidence'' that the other two sisters had tried to kill him out of jealousy. This same scenario was arranged for each of the Sisters of Light. Each was furious that her sisters had turned against her. War broke out between all three sisters, each sister fighting the other two. The Cities of Light were torn apart by a terrible civil war, allowing the Dark Matriarchs to invade, destroying all they envied and hated. The cities were torn down. The temples of learning destroyed. The irrigation systems dammed up and the fertile fields once again claimed by the desert. Small groups of survivors fled into the deserts, becoming wandering nomads drifting through the wastes of the once rich kingdoms of their ancestors.  ')
     , (72799, 17, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'As a reward for his excellent service, the Dark Matriarchs gave Sath''tik the reward they thought he most deserved. They twisted his body to match his warped soul and transformed him into thorn bush, whose leaves would inflict blisters on the skin of any creature that touched them, whose fruit was saturated with deadly poison and whose flowers stank of rotting flesh-all in honor of all the deaths he had caused. Why such a reward? He was male after all and no male should think that he could take down any female, even when ordered, and expect to get away with it. He vowed revenge against all women.  ')
     , (72799, 18, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'All this time, the youngest sister was doing her best to bring her sisters to their senses, but as her Deru masters began to fall to corruption, she realized that there was little she could do. The remaining Deru imbued the youngest sister with eternal youth, by turning her into a spirit that only became corporeal during certain phases of the moons. In such a state, she was unable to save her country or her sisters, but as each sister lay dying, the youngest was able to turn her into a giant bulb with outer leaves so hard neither blade nor magic could penetrate it, so that one day her sisters could be reborn and rejoined so that the Cities of Light could once again rise. In this ghostly form, she was also able to collect the lost teachings of her sisters as well as preserve the teachings of her Deru masters, hiding them in secret grottos and caves so that one day she could show others the way to undo the evil that had been caused by the Dark Matriarchs and their puppet, Sath''tik.  ')
     , (72799, 19, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'As eons slipped by, she passed on what information that she could to her nomad kin, becoming the Lady of Mysteries, finding secrets on the wind. Whenever she can, she leads us, her most loyal descendants, down into the ground where it is said that the Cities of Twilight have grown under her guidance, preparing for the day when we will rise again.  ')
     , (72799, 20, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'For those of us who still wander the Top Lands continue her sacred work. We wander the lands of our fallen kingdom, searching for lost relics and scrolls... any item of knowledge that will be another building block in the reconstruction of our once great society.  ')
     , (72799, 21, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'But ancient knowledge is not enough. We wander, bartering our goods and our knowledge of the desert to traders in exchange for the wisdom of other lands and other peoples. We will be prepared. We will be reborn. And it will be she who leads the way. She, who travels the desert at night in the form of a gromnie, in the light of the smallest moon. She, to whom Rez''arean Ore was sacred, and to whom all whispers wind up murmuring in her ears. She, our Lady of Mysteries, will be our savior. She who will lead us to a new age where darkness is driven from our land for good."  ')
     , (72799, 22, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'It is my sincerest belief, that with all oral traditions, there is truth entwined in this tale. As I have wandered the dunes with Tulith Clan, I have seen enough of the ruins hidden beneath the shifting sands to know there was a great civilization here once. The blast marks on the fallen stones show that great magic was used to bring it down. The clan''s elder has referred to many interesting points that should be investigated further: the temples of learning, the oases and what of these grottos and caves? Could the refugees of this great civil war really have started underground cities?  ')
     , (72799, 23, 0xFFFFFFFF, 'Lady Kahrienne', 'prewritten', False, 'Or perhaps it was a place to hide the scrolls of the destroyed libraries? It is my hope that the Royal Academy will approve my request to continue further into the desert with the hopes of finding proof of not only this once great civilization of triple cities, but also the possibility of a hidden depository of knowledge. Just imagine how such knowledge could help our own kingdom? The potential gain should surely outweigh the costs of further expeditions. I sincerely hope so.  ');
