ReceiveLocalSignal: AerbaxEventCleanup
	- Delay: 60, Motion: Wave
	- StopEvent: aerbaxshadowBooterevent
	- StopEvent: aerbaxelementalprotectorevent
	- StopEvent: aerbaxmosswartprotectorevent
	- StopEvent: aerbaxshadow1event
	- StopEvent: aerbaxshadow2event
	- StopEvent: aerbaxshadow3event
	- StopEvent: aerbaxshadow4event
	- StopEvent: aerbaxshadow5event
	- StopEvent: aerbaxelementalprotectorevent
	- StopEvent: aerbaxsreturnportalevent
	- StopEvent: aerbaxtuskerprotectorevent