ReceiveLocalSignal: EventCleanup
    - Delay: 10, StopEvent: VirindiPortalOneEvent
    - StopEvent: VirindiPortalTwoEvent
    - StopEvent: VirindiPortalThreeEvent
    - StopEvent: VirindiPortalFourEvent
    - StopEvent: VirindiPortalFiveEvent
    - StopEvent: knorrquiddityasheronrewardevent
    - StopEvent: knorrquidditybooterevent
    - StopEvent: KnorrQuiddityFinalRoomEvent
    - StopEvent: KnorrQuiddityTimesUpEvent
    - StopEvent: knorrquiddityasheronevent
